# Ansible playbook for deploying a Flask Web App
---
- name: Deploy Flask web app
 hosts: g1
  become: yes
  

  tasks:
 - name: Add repository
    yum_repository:
      repo: https://download.fedoraproject.org/pub/epel/
      state: present 

  - name: install packages
     package:
      name:
        - python3
        - python3-pip
        - git

  - name: Create the destination folder
      file:
        path: /opt/flaskwebapp
        state: directory

 - name: Clone the repository
      git:
        repo: https://github.com/Elieno/flaskwebapp.git
        dest: /opt/flask-app

- name: Install Flask and its dependencies
      pip:
        name: flask
        virtualenv: /opt/flask-env
        chdir: /opt/flaskwebapp
    become: yes
    
   - name: Start the Flask web app
      command: /var/flask-env/bin/python3 /opt/flaskwebapp/flasktest.py
      async: 1
      poll: 0

